agile-core: # service name matching the resolvable (IP reachable) name if the service container
  swagger_api_spec: ./agile-core.yml
  port: 3300
  calls:
    /device/{deviceId}/status: # api path defined in the swagger api spec
      get:
        entityId: # list of strings | objects{path: string}
          - path: url.deviceId # path where to look the value in
        entityType: device # simple string, won’t get parsed
        field: actions.status # simple string, won’t get parsed
        method: read # simple string, won’t get parsed
    /device/{deviceId}/execute/{command}: # api path defined in the swagger api spec
      get:
        entityId:
          - path: url.deviceId # path where to look the value in
        entityType: device
        field:
          - actions
          - path: url.deviceId # path where to look the value in
          - path: url.command # path where to look the value in
        method: read # simple string, won’t get parsed
